print("True and True ",True and True)
print("False and False ",False and False)
print("1==1 and 2==1 ",1==1 and 2==1)
print("test=test ","test"=="test")
print("1==1 or 2!=1 ",1==1 or 2!=1)
print("True and 1==1 ",True and 1==1)
print("False and 0!=0 ",False and 0!=0)
print("True or 1==1 ",True or 1==1)
print("test=testing ","test"=="testing")

